### ISSUE TITLE
Some songs shows no lyric in win version 0.5.2/0.5.3

### ISSUE THREAD

**Issue by coolguy001tv** [jeffvli/feishin#412]
## Expected Behavior

Show the lyric.

## Current Behavior

In my music lib, there are some songs that have lyrics but feishin shows **no lyrics found**  in windows version, tested on 0.5.2 and 0.5.3. But in docker version 0.5.2, feishin shows the lyric.

I noticed there is **lyrics** param both in win and docker version, but the win version shows no lyric as picture below:
![1702608230430](https://github.com/jeffvli/feishin/assets/936825/038878de-56f7-4e5a-aa36-afc42f97b56a)

It happens only on a few songs, many other songs show the right lyrics.

## Steps to Reproduce

Unzip this song to your server ( I use navidrome), use feishin win version to play it, and switch to LYRICS tab to see if there's lyric or not.

[Sum 41 - Still Waiting.zip](https://github.com/jeffvli/feishin/files/13680377/Sum.41.-.Still.Waiting.zip)

## Possible Solution (Not obligatory)

I don't know if it's something uncompatible in the lyric which made feishin can't parse the lyric?
here's the lyric of the song(copy from the lyrics param in the picture above):

> [by:blackerXHunter]
[00:00.00]作词 : sum41
[00:00.27]作曲 : sum41
[00:00.55]So am I still waiting 所以我仍在等待
[00:03.11]For this world to stop hating 等待世人放下仇恨与偏见
[00:05.63]Can't find a good reason 但却找不到可以依赖的理由
[00:08.90]Can't find hope to believe in 找不到可以相信的希望
[00:21.80]Drop dead a bullet to my head 子弹穿过头颅
[00:24.32]Your words are like a gun in hand 你的言语犹如手中的枪
[00:26.76]You can't change the state of the nation 你无法改变这个国家的现状
[00:29.18]We just need some motivation 我们只需要前进的动力
[00:31.73]These eyes have seen no conviction 空洞眼眶不见信仰
[00:34.15]Just lies and more contradiction 只剩下自我矛盾的谎言
[00:36.74]So tell me what would you say 告诉我你会说什么
[00:39.18]I'd say its up: to me 我会说这由我做主
[00:42.73]So am I still waiting 因此我继续期盼
[00:45.60]For this world to stop hating 等这个世界冰释前嫌
[00:48.11]Can't find a good reason 找不到完美解释
[00:50.55]Can't find hope to believe in 寻不见可以相信的希望
[00:58.80]Ignorance and Understanding 无知和理解
[01:00.53]We're the first ones to jump in line 我们首先跨进禁区
[01:03.70]Out of step for what we believe in 为了理想跨出一步
[01:05.50]But whos left? To start the pleading 但是谁能留下？开始辩论
[01:08.10]How far will we take this 我们能坚持走多远
[01:10.51]It's not hard to see through the sickness 病态已破,假象败露
[01:13.10]So tell me what would you say 告诉我你会说什么
[01:15.59]I'd say: its up to me 我会说这由我做主
[01:18.98]So am I still waiting 因此我继续期盼
[01:21.83]For this world to stop hating 等这个世界冰释前嫌
[01:24.33]Can't find a good reason 找不到完美解释
[01:26.76]Can't find hope to believe in 寻不见可以相信的希望
[01:29.30]This can't last forever 这不会持续很久的
[01:33.97]Time won't make things better 时间不会让一切更好
[01:39.90]I feel so alone 孤立无援
[01:42.36]Can't help myself 难以自拔
[01:44.90]And no one knows 无人知晓
[01:46.93]If this is worthless to me 毫无价值
[02:04.35]What have we done 我们做了什麼
[02:06.83]We're in a war that can't be won 我们在这场无法取胜的战争中
[02:09.35]This can't be real 这不可能是真的
[02:11.81]I don't know what to feel 我不知道是这什么感觉
[02:15.54]So am I still waiting 因此我继续期盼
[02:18.79]For this world to stop hating 等这个世界冰释前嫌
[02:20.57]Can't find a good reason 找不到完美解释
[02:23.50]Can't find hope to believe in 找不到完美解释
[02:25.62]So am I still waiting 所以我仍在等待着
[02:28.30]For this world to stop hating 等这个世界冰释前嫌
[02:30.51]Can't find a good reason 找不到完美解释
[02:32.99]Can't find hope to believe in 找不到可以相信的希望

## Context

I tried switching Audio play from MPV to Web and they are the same. 

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.2/0.5.3 
-   Operating System and version (e.g. Windows 10) : windows 11
-   Server and version (e.g. Navidrome v0.48.0) :  Navidrome v0.50.1
-   Node version (if developing locally) :

**Comment by iiPythonx** [comment]
Running Navidrome 0.51 w/ Feishin built from source, the lyrics now load fine:

![image](https://github.com/jeffvli/feishin/assets/35084023/55ffed98-bf19-4ff7-afca-817eb50497c0)

Gonna assume this was fixed by https://github.com/jeffvli/feishin/pull/484, somewhere during the Navidrome lyrics restructure.

**Comment by coolguy001tv** [comment]
Thanks for the reply. It's not easy for me to build Feishin from source, so I'd like to wait the next version 0.5.4 to check if it's resolved.

**Comment by kgarner7** [comment]
You don't need to build it, you can use any of the PR actions that build packages (like https://github.com/jeffvli/feishin/actions/runs/7771900425)

**Comment by coolguy001tv** [comment]
Thanks. 
First I upgrade my navidrome to latest(0.51.1), with  the feishin above(https://github.com/jeffvli/feishin/actions/runs/7771900425) or the latest PR action build, but the song's lyric still doesn't show.
The I delete the navidrome cache folder and the db (for people whoever encounters this problem: always remeber to **back up** your database), the the song's lyric shows all right.
Although my docker version's feishin occurs some problems after my navidrome upgrading to the latest, it's out of this topic. This win version's problem has been solved. So I close this.
